apiVersion: v1
kind: Pod
metadata:
    name: node-app-pod
    labels:
      name: node-app-pod
      app: node-app
      type: front-end
spec:
  containers:
    - name: nodejs-pod
      image: fafto/nodejs
      ports:
        - containerPort: 3000

