apiVersion: v1
kind: Service
metadata:
    name: node-app-service
spec:
    type: NodePort
    ports:
      - targetPort: 3000
        port: 3000
        nodePort: 30000
    selector:
      name: node-app-pod
      app: node-app
      type: front-end

  